# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a436d3e93d677c6d283c140dc0e89ac142d2ccd9ee5b00f7789ef01ddbf80b0d010bfd0024a4f1a7c7f2a4fdb4b3223714f3001e8055b5d0285dac0dd387a14c

test:
  secret_key_base: c85ee3a7ceae2dfcfd779ed589d24200e7bfe4c4423e0696081f5ef30c84fa01bdcefed6f118a60d47362036e68f0fd5d5a3bbebc60ed54c7d42767772caa862

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
